server:
  port: 8080

dubbo:
  registry:
    id: ${DUBBO_REGISTORY_ID}
    address: www.modutxt.xin:2181
    protocol: zookeeper
  application:
    id: travel_api_id1
    name: travel_api_name1
token:
  secret: ${SECRET_TOKEN}
  algorithm: HS256
  expiresSecond: ${TOKEN_EXPIRES_SECOND}